### ISSUE TITLE
Installation halted at first step [ Bug ]

### ISSUE THREAD

**Issue by HagRetek** [valknight/Splatnet2-Rich-Presence#7]
### Description 

I ran **setup.py** and at the very first step of the installation (`Installing requirements...`) it halted with an error code I wrote at **\#\#\# Output**, then it tried `Installing as a user package`. That failed too.
> I would like to note that I ran cmd as an administrator.

### Output

```shell
[ 17:11:24 13-01-2019 ] [ INFO ] Installing requirements...
Command "C:\Users\Hag\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Hag\\AppData\\Local\\Temp\\pip-install-01pt4bhi\\brotlipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Hag\AppData\Local\Temp\pip-record-q7zsohl7\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Hag\AppData\Local\Temp\pip-install-01pt4bhi\brotlipy\
[ 17:11:41 13-01-2019 ] [ ERROR ] Failed to instal system wide (we recommend a venv if you're not!
[ 17:11:41 13-01-2019 ] [ INFO ] Attempting to install as a user package
Command "C:\Users\Hag\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Hag\\AppData\\Local\\Temp\\pip-install-98vuxu39\\brotlipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\UsersHag\AppData\Local\Temp\pip-record-ybdua6fd\install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in C:\Users\Hag\AppData\Local\Temp\pip-install-98vuxu39\brotlipy\
[ 17:11:55 13-01-2019 ] [ INFO ] Something went wrong while installing requirements. Check your python setup and permissions.
```

### Specs

 - **OS:** Windows 10 Home, build 17134.523 (before you say *update windows*, I can't update it, I've had multiple freezes while trying to update)
 - **Python:** version 3.7.2 (I have reinstalled it earlier today, I cannot find any permissions that would cause the installation to halt)

### I tried to investigate, but...

after running `cd Users\Hag\AppData\Local\Temp\pip-install-98vuxu39\` (at the root of drive C:\\)in hopes of finding the file, it said `A rendszer nem találja a megadott elérési utat.`, basically, the system couldn't find the directory.
So, I ran `where brotlipy`, at the root of drive C:\ again (so it would scan the entire drive). But the system couldn't find any files matching **brotlipy**.

**Comment by valknight** [comment]
Huh, this is odd. Could you run `python.exe -m pip install -r requirements.txt` (replace python.exe with python3.exe if that's what it's named on your system) and see whether that gives the same issue? This seems like a requirement is failing to install on your environment, but I just want to confirm that before moving on.

**Comment by valknight** [comment]
Okay, I just tested on laptop, and all seems fine - https://i.imgur.com/1729gNA.png

I'm guessing it may be something to do with 32-bit python on Windows, as everything seems fine here on Linux, but I don't have a Windows machine at the moment to confirm that.

**Comment by HagRetek** [comment]
I can maybe try it in Ubuntu, now that there's a new version of Discord. But I'll still try the method you gave me ob Windows.

**Comment by valknight** [comment]
Awesome, if you report back whether it works or not that would be fantastic.

**Comment by valknight** [comment]
Install python3-pip.

**Comment by HagRetek** [comment]
Welp, I tried... Installation of pip done and all, but `setup.py` still wouldn't even work.

**Comment by valknight** [comment]
Can you give a log of what's happening? Sorry for being annoying, but I can't see your system, and saying it's not working doesn't help much.

**Comment by HagRetek** [comment]
Now I'm using Ubuntu 18.04.1 right now. As I said, pip succesfully installed everything from `requirements.txt` but the errors when running `setup.py` are the same as in the initial comment.

I also got a popup window saying `__init__.py` has crashed

**Comment by valknight** [comment]
Okay, can you give me the output of `[python executable] --version` and the pip version as well?

**Comment by HagRetek** [comment]
Pip: `pip 9.0.1`
Pyhton: `Python 3.6.7`

everything has just been updated using `sudo apt update`

**Comment by valknight** [comment]
`sudo apt update` doesn't update the system, are you sure you didn't mean to run `sudo apt upgrade`

**Comment by HagRetek** [comment]
done that as well, but still nothing

**Comment by valknight** [comment]
Ok, had a look over your edit with logs - a segmentation fault isn't normal, as that's usually an issue with python or a related library that's compiled in C. Can you install + run `neofetch`, and copy the output here (ofc redacting any personal info if it spits it out)

**Comment by HagRetek** [comment]
copy the output of `sudo apt install neofetch`?

**Comment by valknight** [comment]
No, install it, them copy the output of what happens when you run it

**Comment by HagRetek** [comment]
oh, yea, neofetch is this program that outputs the system info...

```shell
            .-/+oossssoo+/-.               hag@hag-ubuntu 
        `:+ssssssssssssssssss+:`           ----------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 20238 Lenovo G510 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.15.0-29-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 42 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2109 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.19 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1366x768 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 3.28.3 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: GNOME Shell 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Ambiance [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Communitheme [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-4700MQ (8) @ 3.400GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: AMD Radeon R7 M265 
      -+sssssssssssssssssyyyssss+-         GPU: Intel Haswell Mobile 
        `:+ssssssssssssssssss+:`           Memory: 2769MiB / 7888MiB 
            .-/+oossssoo+/-. 
```

**Comment by valknight** [comment]
DW about the ubuntu logo, it's all chill. That all seems fine, I just wanted to check there wasn't anything funky going on. 

Okay, can you run `python3 -m pip install –upgrade pip`? I have a feeling pip is out of date, and pip isn't updated by apt all the time. 

If that doesn't fix the issue, create a virtual environment with `python3 -m venv venv/` in the directory you've cloned this tool to. Then run `source venv/bin/activate` and then `python setup.py`.

**Comment by HagRetek** [comment]
`python3 -m pip install -upgrade pip` output:

```Invalid requirement: '–upgrade'
Traceback (most recent call last):
  File "/usr/share/python-wheels/packaging-17.1-py2.py3-none-any.whl/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1632, in parseString
    raise exc
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 3378, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl/pyparsing.py", line 2689, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/usr/share/python-wheels/packaging-17.1-py2.py3-none-any.whl/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'–upgrade'"
```
I tried installing in a virtual enviroment, but the errors are still the same...

**Comment by valknight** [comment]
Oh sorry, it's `--upgrade`, not `-upgrade`

**Comment by HagRetek** [comment]
pip is installed succesfully, but still, same error again...

no need to stress yourself about this, i just have absolutely no idea why this happened.

**Comment by valknight** [comment]
Yeah, seg fault is usually a sign your python is completely fucked beyond repair.

However, can you install the requirements with the normal pip way? It's not ideal, but, it then means you'd be able to run the tool itself, and we can see whether it's a bigger issue with your python, or just an issue with setup.py + your python.

**Comment by HagRetek** [comment]
what do you mean under *install pip the normal way*? I used `sudo apt install python3-pip`

**Comment by HagRetek** [comment]
Also, here is a new line i havent seen before:
```shell
sh: 1: /home/hag/Asztal/Programok/Discord/Rich: not found
```
This is probably because you didnt put the path as a string somewhere in the script. *Rich Presence* only gets found when it is put between quotation marks in the code, as it has a space in the name.
I'll try renaming it and then I'll try running the script again. or do i need to reinitialize the venv if i do changes to the files?

**Comment by HagRetek** [comment]
renamed all the folders (removed the spaces between words in the names) and now the script works perfectly fun.

```shell
[ 15:35:36 20-01-2019 ] [ INFO ] Requirements installed! Go have some fun!
```

**Comment by HagRetek** [comment]
now i have a question real quick...
i have the proxy the script gave me set on my phone and i am currently in the nso app. but still, nothing's happening.

**Comment by valknight** [comment]
Setup.ink should redirect to a page which lets you install the certificate used for intercepting NSO traffic. If it's not working, make sure the proxy is set right, and if that fails, try an android emulator

**Comment by valknight** [comment]
And cool, I'll patch up the installer to work with paths including spaces

**Comment by valknight** [comment]
If more information is given, we can reopen.
